import { ORIGIN } from './blog-db.js'
import { escape as e, contentHtml } from './blog-content.js'
export const imageUrl = post => post.cover_id ? `${ORIGIN}/blog/capa/${post.cover_id}` : `${ORIGIN}/social-card.jpg`
const date = value => new Date(value).toLocaleDateString('pt-BR',{day:'numeric',month:'long',year:'numeric',timeZone:'America/Sao_Paulo'})
const minutes = text => Math.max(1,Math.ceil(text.split(/\s+/).length/200))
export function layout({title,description,path,html,image=`${ORIGIN}/social-card.jpg`,schema,type='website',noindex=false}) {
  const canonical=ORIGIN+path
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(description)}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow,max-image-preview:large'}"><link rel="canonical" href="${e(canonical)}"><link rel="icon" href="/favicon-32.png"><link rel="preload" href="/fonts/manrope-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/blog.css"><meta property="og:type" content="${type}"><meta property="og:locale" content="pt_BR"><meta property="og:site_name" content="Grupo YR Hospitalar"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${e(image)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${e(title)}"><meta name="twitter:description" content="${e(description)}"><meta name="twitter:image" content="${e(image)}">${schema?`<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script>`:''}</head><body><a class="skip" href="#conteudo">Ir para o conteúdo</a><header class="blog-header"><a class="blog-brand" href="/" aria-label="Grupo YR Hospitalar — início"><img src="/yr-hospitalar-logo.jpg" alt="Grupo YR Hospitalar" width="1280" height="1280"></a><nav aria-label="Navegação principal"><a href="/#produtos">Equipamentos</a><a href="/blog" aria-current="${path==='/blog'?'page':'false'}">Blog YR</a><a class="pill" href="/#contato">Vamos conversar ↗</a></nav></header><main id="conteudo">${html}</main><footer class="blog-footer"><div><a href="/">Grupo YR Hospitalar</a><p>Soluções que transformam saúde.</p></div><nav aria-label="Navegação do rodapé"><a href="/#produtos">Equipamentos</a><a href="/comprar-ou-alugar">Compra ou locação</a><a href="mailto:rodrigo@grupoyrhospitalar.com.br">Fale com a YR ↗</a></nav><p>© ${new Date().getFullYear()} Grupo YR Hospitalar.</p></footer></body></html>`
}
export function card(post,index=0) {
  return `<a class="story-card ${index===0?'story-featured':''}" href="/blog/${e(post.slug)}"><div class="story-image"><img src="${imageUrl(post).replace(ORIGIN,'')}" alt="${e(post.cover_alt||post.title)}" width="1200" height="800" ${index===0?'fetchpriority="high"':'loading="lazy"'}><span class="round-arrow" aria-hidden="true">↗</span></div><div class="story-copy"><div class="eyebrow">${e(post.category)} <span>•</span> ${minutes(post.body)} min de leitura</div><h2>${e(post.title)}</h2><p>${e(post.excerpt)}</p><span class="story-date">${date(post.published_at)}</span></div></a>`
}
export function indexPage(posts,total,page,query) {
  const filtered=Boolean(query), title='Blog YR | Guias sobre equipamentos hospitalares',description='Informação para planejar melhor: guias de compra, locação, entrega e organização de equipamentos hospitalares com o Grupo YR.'
  const next=(n)=>`/blog?${new URLSearchParams({...query?{q:query}:{},pagina:String(n)})}`
  const html=`<section class="journal-hero"><div class="eyebrow"><span class="live-dot"></span> Caderno YR / Informação que aproxima</div><div class="journal-title"><h1>Boas escolhas<br>começam com <em>clareza.</em></h1><p>Um espaço para entender, organizar e seguir em frente. Guias práticos para quem cuida e para quem faz a saúde acontecer.</p></div><form action="/blog" class="blog-search" role="search"><label for="q">O que você quer entender melhor?</label><div><input id="q" name="q" type="search" maxlength="100" value="${e(query)}" placeholder="Busque por entrega, locação, equipamentos…"><button class="pill" type="submit">Buscar <span aria-hidden="true">↗</span></button></div></form></section><section class="journal-stories" aria-labelledby="stories-title"><div class="section-line"><h2 id="stories-title">${filtered?`Resultados para “${e(query)}”`:'Para sua próxima decisão'}</h2><span>${total} ${total===1?'artigo':'artigos'}${filtered?' · <a href="/blog">Limpar busca</a>':''}</span></div>${posts.length?`<div class="stories-grid">${posts.map(card).join('')}</div>`:'<div class="empty-state"><h2>A próxima leitura está a caminho.</h2><p>Experimente outra busca ou explore os equipamentos da YR.</p><a class="pill" href="/#produtos">Explorar equipamentos ↗</a></div>'}<nav class="pagination" aria-label="Páginas do blog">${page>1?`<a class="pill secondary" href="${e(next(page-1))}">← Anteriores</a>`:''}${page*9<total?`<a class="pill" href="${e(next(page+1))}">Próximos artigos →</a>`:''}</nav></section><aside class="journal-cta"><span class="eyebrow">Da informação à ação</span><h2>Sua necessidade.<br>Uma conversa de cada vez.</h2><a class="pill light" href="/#contato">Conte com a YR ↗</a></aside>`
  return layout({title,description,path:page>1?`/blog?pagina=${page}`:'/blog',html,noindex:filtered,schema:{'@context':'https://schema.org','@type':'Blog',name:'Blog YR',url:ORIGIN+'/blog',inLanguage:'pt-BR',blogPost:posts.map(p=>({'@type':'BlogPosting',headline:p.title,url:ORIGIN+'/blog/'+p.slug,datePublished:new Date(p.published_at).toISOString()}))}})
}
export function articlePage(post,related) {
  const title=post.seo_title||`${post.title} | Blog YR`,description=post.seo_description||post.excerpt,path='/blog/'+post.slug
  const schema={'@context':'https://schema.org','@graph':[{'@type':'BlogPosting','@id':ORIGIN+path+'#article',headline:post.title,description,image:[imageUrl(post)],datePublished:new Date(post.published_at).toISOString(),dateModified:new Date(post.updated_at).toISOString(),author:{'@type':'Organization',name:'Grupo YR Hospitalar',url:ORIGIN+'/'},publisher:{'@type':'Organization',name:'Grupo YR Hospitalar',logo:{'@type':'ImageObject',url:ORIGIN+'/yr-hospitalar-logo.jpg'}},mainEntityOfPage:ORIGIN+path,inLanguage:'pt-BR'},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Início',item:ORIGIN+'/'},{'@type':'ListItem',position:2,name:'Blog YR',item:ORIGIN+'/blog'},{'@type':'ListItem',position:3,name:post.title,item:ORIGIN+path}]}]}
  return layout({title,description,path,image:imageUrl(post),schema,type:'article',html:`<article class="article"><nav class="breadcrumb" aria-label="Você está em"><a href="/">Início</a><span>/</span><a href="/blog">Blog YR</a><span>/</span><span>${e(post.category)}</span></nav><header class="article-heading"><div class="eyebrow">${e(post.category)} <span>•</span> ${minutes(post.body)} min de leitura</div><h1>${e(post.title)}</h1><p class="article-lede">${e(post.excerpt)}</p><div class="article-byline"><span class="author-mark">YR</span><div><strong>Grupo YR Hospitalar</strong><span>Publicado em ${date(post.published_at)}${new Date(post.updated_at)-new Date(post.published_at)>86400000?` · Atualizado em ${date(post.updated_at)}`:''}</span></div></div></header>${post.cover_id?`<figure class="article-cover"><img src="${imageUrl(post).replace(ORIGIN,'')}" alt="${e(post.cover_alt)}" width="1600" height="1000" fetchpriority="high"></figure>`:''}<div class="article-layout"><aside class="article-aside"><span class="eyebrow">Seu próximo passo</span><p>Transforme sua leitura em uma conversa.</p><a class="pill" href="/#contato">Fale com a YR ↗</a><a href="/blog">← Todos os artigos</a></aside><div class="article-prose">${contentHtml(post.body)}<div class="article-end"><p>Precisa organizar sua cotação?</p><a class="pill" href="/#produtos">Conheça os equipamentos ↗</a></div></div></div></article>${related.length?`<section class="journal-stories related"><div class="section-line"><h2>Continue por aqui.</h2><a href="/blog">Todo o caderno ↗</a></div><div class="stories-grid">${related.map((p,i)=>card(p,i+1)).join('')}</div></section>`:''}`})
}
